spring:
  application:
    name: upwfree
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    cache: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# Scheduled job configuration
app:
  products:
    fetch:
      url: https://famme.no/products.json
      limit: 50