spring:
  application:
    name: upwfree
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  thymeleaf:
    cache: false

server:
  port: 8080

# Scheduled job configuration
app:
  products:
    fetch:
      url: https://famme.no/products.json
      limit: 50

# Logging
logging:
  level:
    org.springframework.web: INFO
    com.example.upwfree: DEBUG